export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";

export const ADD_CONTACTDATA = "ADD_CONTACTDATA";
export const GET_CONTACTDATA = "GET_CONTACTDATA";
export const CONTACTDATA_FAILED = "CONTACTDATA_FAILED";

export const ADD_AUTHDATA = "ADD_AUTHDATA";
export const AUTH_FAILED = "AUTH_FAILED";
